### ISSUE TITLE
ImportError: No module named "request"

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#36]
When I ran the program, Python gave me a ImportError. Here is a more detailed version of the error:
<pre><code>Traceback (most recent call last):
  File "C:\Python27\Ways-to-NOT-make-money-master\game.py", line 4, in <module>
    from github import Github
  File "C:\Python27\github\__init__.py", line 36, in <module>
    from .MainClass import Github
  File "C:\Python27\github\MainClass.py", line 28, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request
</code></pre>

See also: #376 https://github.com/PyGithub/PyGithub/issues/376

**Comment by qlstudio** [comment]
Fixed, just need to reinstall pygithub
