### ISSUE TITLE
NameError: global name 'timevar' is not defined

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#8]
I ran the program and clicked the AutoClick button, but before I got three dollars by AutoClick: I got this error:

    Exception in Tkinter callback
    Traceback (most recent call last):
      File "C:\Python27\lib\lib-tk\Tkinter.py", line 1486, in __call__
        return self.func(*args)
      File "C:\Python27\lib\lib-tk\Tkinter.py", line 533, in callit
        func(*args)
      File "C:\Python27\Ways-to-NOT-make-money-master\game.py", line 330, in automoney
        timevar.set("Total time: " + str(time))
    NameError: global name 'timevar' is not defined

**Comment by DerpfacePython** [comment]
Fixed in V0.5.3-3 (changed the global thing a bit).
