### ISSUE TITLE
create account broken in py2 version

### ISSUE THREAD

**Issue by joshgit** [DerpfacePython/Ways-to-NOT-make-money#91]
Yes
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1539, in __call__
    return self.func(*args)
  File "game.py", line 79, in createaccount
    game_state = game_model.GameState(g2)
  File "/home/josh/Desktop/coding/Ways-to-NOT-make-money/py2/game_model.py", line 53, in __init__
    self.lottoprice = int(self.data[45])
IndexError: list index out of range

**Comment by joshgit** [comment]
Login also broken under py3 version, with similar error message.

**Comment by qlstudio** [comment]
The login was broken with index 45.

**Comment by DerpfacePython** [comment]
We might need to fix the `auto-updater` for that. Also, probably fixed in V0.7.2 (which was fused).

**Comment by qlstudio** [comment]
Er...
```python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
================= RESTART: C:\Python27\Ways-to-NOT-make-money-master\py2\game.py =================
Yes
game model self.data ['auto', '0', 'print', '0', 'counter', '0', 'shares', '0', 'bank', '0', 'upg1h1', '0', 'upg1h2', '0', 'upg2h1', '0', 'upg2h2', '0', 'upg3', '0', 'upg4', '0', 'upg5', '0', 'cupg1', '0', 'cupg2', '0', 'quintillion', '0', 'quadrillion', '0', 'trillion', '0', 'billion', '0', 'million', '0', 'money', '0.0', 'time', '0', 'clicks', '0']
game_state <game_model.GameState instance at 0x030862D8>
g2 ['auto', '0', 'print', '0', 'counter', '0', 'shares', '0', 'bank', '0', 'upg1h1', '0', 'upg1h2', '0', 'upg2h1', '0', 'upg2h2', '0', 'upg3', '0', 'upg4', '0', 'upg5', '0', 'cupg1', '0', 'cupg2', '0', 'money', '0.0', 'time', '0', 'clicks', '0', 'lotto', '0']
update ['auto', '0', 'print', '0', 'counter', '0', 'shares', 'bank', 0, '0', 'upg1h1', '0', 'upg1h2', '0', 'upg2h1', '0', 'upg2h2', '0', 'upg3', '0', 'upg4', '0', 'upg5', 'upg5', 0, '0', 'cupg2', '0', 'money', '0.0', 'time', '0', 'clicks', '0', 'lotto', '0', 'time', 0, 'clicks', 0, 'lotto', 100]
game model self.data ['auto', '0', 'print', '0', 'counter', '0', 'shares', 'bank', 0, '0', 'upg1h1', '0', 'upg1h2', '0', 'upg2h1', '0', 'upg2h2', '0', 'upg3', '0', 'upg4', '0', 'upg5', 'upg5', 0, '0', 'cupg2', '0', 'money', '0.0', 'time', '0', 'clicks', '0', 'lotto', '0', 'time', 0, 'clicks', 0, 'lotto', 100]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "C:\Python27\Ways-to-NOT-make-money-master\py2\game.py", line 62, in verifysignin
    game_state = game_model.GameState(g2)
  File "C:\Python27\Ways-to-NOT-make-money-master\py2\game_model.py", line 23, in __init__
    self.upgcheck5 = int(self.data[23])
ValueError: invalid literal for int() with base 10: 'upg5'
>>> 
```

- [ ] The game screen doesn't display after creating account.
- [ ] The `IndexError`

**Comment by DerpfacePython** [comment]
Yeah, we definitely need to fix `auto_updater` to accommodate for stuff.

**Comment by testitem** [comment]
Wait- is it fixed or not? @DerpfacePython @joshgit ? You haven't been active for a while.
